import api from './client';
const b = (w) => `/workspaces/${w}`;
export const getYears      = (w,p)      => api.get(`${b(w)}/years`,{params:p}).then(r=>r.data);
export const createYear    = (w,d)      => api.post(`${b(w)}/years`,d).then(r=>r.data);
export const updateYear    = (w,id,d)   => api.put(`${b(w)}/years/${id}`,d).then(r=>r.data);
export const archiveYear   = (w,id)     => api.post(`${b(w)}/years/${id}/archive`).then(r=>r.data);
export const restoreYear   = (w,id)     => api.post(`${b(w)}/years/${id}/restore`).then(r=>r.data);
export const deleteYear    = (w,id)     => api.delete(`${b(w)}/years/${id}`).then(r=>r.data);
export const getGroups     = (w,y,p)    => api.get(`${b(w)}/years/${y}/groups`,{params:p}).then(r=>r.data);
export const createGroup   = (w,y,d)    => api.post(`${b(w)}/years/${y}/groups`,d).then(r=>r.data);
export const updateGroup   = (w,y,id,d) => api.put(`${b(w)}/years/${y}/groups/${id}`,d).then(r=>r.data);
export const archiveGroup  = (w,y,id)   => api.post(`${b(w)}/years/${y}/groups/${id}/archive`).then(r=>r.data);
export const restoreGroup  = (w,y,id)   => api.post(`${b(w)}/years/${y}/groups/${id}/restore`).then(r=>r.data);
export const deleteGroup   = (w,y,id)   => api.delete(`${b(w)}/years/${y}/groups/${id}`).then(r=>r.data);
export const getExpenses   = (w,p)      => api.get(`${b(w)}/expenses`,{params:p}).then(r=>r.data);
export const createExpense = (w,d)      => api.post(`${b(w)}/expenses`,d).then(r=>r.data);
export const updateExpense = (w,id,d)   => api.put(`${b(w)}/expenses/${id}`,d).then(r=>r.data);
export const archiveExpense= (w,id)     => api.post(`${b(w)}/expenses/${id}/archive`).then(r=>r.data);
export const restoreExpense= (w,id)     => api.post(`${b(w)}/expenses/${id}/restore`).then(r=>r.data);
export const deleteExpense = (w,id)     => api.delete(`${b(w)}/expenses/${id}`).then(r=>r.data);
export const upsertSalary  = (w,d)      => api.post(`${b(w)}/salary-entries`,d).then(r=>r.data);
export const getArchiveLog = (w)        => api.get(`${b(w)}/archive-log`).then(r=>r.data);
export const importData    = (w,data)   => api.post(`${b(w)}/import`,data).then(r=>r.data);
