import api from './client';
const b = (w) => `/workspaces/${w}`;
export const getLoans       = (w,p)         => api.get(`${b(w)}/loans`,{params:p}).then(r=>r.data);
export const createLoan     = (w,d)         => api.post(`${b(w)}/loans`,d).then(r=>r.data);
export const updateLoan     = (w,id,d)      => api.put(`${b(w)}/loans/${id}`,d).then(r=>r.data);
export const deleteLoan     = (w,id)        => api.delete(`${b(w)}/loans/${id}`).then(r=>r.data);
export const getInvestments = (w)           => api.get(`${b(w)}/investments`).then(r=>r.data);
export const createInv      = (w,d)         => api.post(`${b(w)}/investments`,d).then(r=>r.data);
export const updateInv      = (w,id,d)      => api.put(`${b(w)}/investments/${id}`,d).then(r=>r.data);
export const deleteInv      = (w,id)        => api.delete(`${b(w)}/investments/${id}`).then(r=>r.data);
export const getInsurance   = (w)           => api.get(`${b(w)}/insurance`).then(r=>r.data);
export const createIns      = (w,d)         => api.post(`${b(w)}/insurance`,d).then(r=>r.data);
export const updateIns      = (w,id,d)      => api.put(`${b(w)}/insurance/${id}`,d).then(r=>r.data);
export const deleteIns      = (w,id)        => api.delete(`${b(w)}/insurance/${id}`).then(r=>r.data);
export const getBanks       = (w)           => api.get(`${b(w)}/banks`).then(r=>r.data);
export const createBank     = (w,d)         => api.post(`${b(w)}/banks`,d).then(r=>r.data);
export const updateBank     = (w,id,d)      => api.put(`${b(w)}/banks/${id}`,d).then(r=>r.data);
export const deleteBank     = (w,id)        => api.delete(`${b(w)}/banks/${id}`).then(r=>r.data);
export const createSection  = (w,bid,d)     => api.post(`${b(w)}/banks/${bid}/sections`,d).then(r=>r.data);
export const updateSection  = (w,bid,id,d)  => api.put(`${b(w)}/banks/${bid}/sections/${id}`,d).then(r=>r.data);
export const deleteSection  = (w,bid,id)    => api.delete(`${b(w)}/banks/${bid}/sections/${id}`).then(r=>r.data);
export const createEntry    = (w,bid,sid,d)       => api.post(`${b(w)}/banks/${bid}/sections/${sid}/entries`,d).then(r=>r.data);
export const updateEntry    = (w,bid,sid,id,d)    => api.put(`${b(w)}/banks/${bid}/sections/${sid}/entries/${id}`,d).then(r=>r.data);
export const deleteEntry    = (w,bid,sid,id)      => api.delete(`${b(w)}/banks/${bid}/sections/${sid}/entries/${id}`).then(r=>r.data);
export const getOverview    = (w)           => api.get(`${b(w)}/overview`).then(r=>r.data);
export const createOverview = (w,d)         => api.post(`${b(w)}/overview`,d).then(r=>r.data);
export const updateOverview = (w,id,d)      => api.put(`${b(w)}/overview/${id}`,d).then(r=>r.data);
export const deleteOverview = (w,id)        => api.delete(`${b(w)}/overview/${id}`).then(r=>r.data);
